### ISSUE TITLE
Runtime Update

### ISSUE THREAD

**Issue by Justinzobel** [flathub/org.kde.Ikona#4]
Please consider upgrading to a Qt6 runtime if your application supports Qt6, or 5.15-2308 otherwise.

**Comment by tsdgeos** [comment]
ikona is "dead" https://invent.kde.org/sdk/ikona/

**Comment by Justinzobel** [comment]
Shall we begin the EOL task then?

**Comment by travier** [comment]
I think we can just leave this one as is. It's there if someone wants to use it. We don't need to touch it anymore.
